# Generated by Django 6.1.1 on 2026-09-17 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelance', '0005_education_date_obtention_education_etablissement_and_more'),
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre_motivation', models.TextField(max_length=5000)),
                ('date_livraison', models.DateTimeField()),
                ('proposition_status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='freelance.freelancee')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='mission.mission')),
            ],
        ),
    ]
