# Generated by Django 6.1.1 on 2026-09-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0005_education_date_obtention_education_etablissement_and_more'),
        ('mission', '0001_initial'),
        ('proposition', '0002_proposition_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='date_livraison',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='proposition',
            constraint=models.UniqueConstraint(fields=('freelance', 'mission'), name='unique_proposition_per_freelance_and_mission'),
        ),
    ]
