# Generated by Django 6.1.1 on 2026-09-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='user_id',
        ),
    ]
