# Generated by Django 6.1.1 on 2026-09-16 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Service', '0002_alter_service_options_remove_service_user_id'),
        ('announcer', '0002_alter_announcer_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('date_deadline', models.DateField(blank=True, null=True)),
                ('operateurMobileMoney', models.CharField(choices=[('OM', 'Orange Money'), ('WAVE', 'Wave')], max_length=50)),
                ('budget', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annonceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcer.announcer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.service')),
            ],
        ),
    ]
