# Generated by Django 6.1.1 on 2026-09-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ouverte'), ('IN_PROGRESS', 'En cours de développement'), ('COMPLETED', 'Terminée'), ('CLOSED', 'Fermée')], default='OPEN', max_length=20),
        ),
    ]
