# Generated by Django 6.1.1 on 2026-09-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technologie', '0001_initial'),
        ('mission', '0002_mission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='missions', to='Technologie.technologie'),
        ),
    ]
