# Generated by Django 6.1.1 on 2026-09-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_alter_service_options_remove_service_user_id'),
        ('User', '0002_user_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='users', to='Service.service'),
        ),
    ]
