# Generated by Django 6.1.1 on 2026-09-14 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_alter_service_options_remove_service_user_id'),
        ('User', '0003_user_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='service',
        ),
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Service.service'),
        ),
    ]
