# Generated by Django 6.1.1 on 2026-09-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_user_service_user_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='technologies',
        ),
    ]
