# Generated by Django 6.1.1 on 2026-09-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_user_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('freelance', 'Freelance'), ('annonceur', 'Annonceur')], max_length=20, null=True),
        ),
    ]
