# Generated by Django 6.1.1 on 2026-09-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='service',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_step',
            field=models.CharField(default='identite', max_length=50),
        ),
    ]
