# Generated by Django 6.1.1 on 2026-09-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technologie', '0001_initial'),
        ('freelance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancee',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='technologies', to='Technologie.technologie'),
        ),
    ]
