# Generated by Django 6.1.1 on 2026-09-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technologie', '0001_initial'),
        ('freelance', '0002_freelancee_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancee',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='freelance_profiles', to='Technologie.technologie'),
        ),
    ]
