# Generated by Django 6.1.1 on 2026-09-15 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_alter_service_options_remove_service_user_id'),
        ('freelance', '0003_alter_freelancee_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancee',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='Service.service'),
        ),
        migrations.AlterField(
            model_name='education',
            name='role',
            field=models.CharField(choices=[('UNIVERSITAIRE', 'Universitaire'), ('FORMATION_PROFESSIONNELLE', 'Formation professionnelle'), ('EN_LIGNE', 'En ligne')], max_length=100),
        ),
    ]
