# Generated by Django 6.1.1 on 2026-09-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0004_freelancee_service_alter_education_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='date_obtention',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='etablissement',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='intitule',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='lien_verification',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='realisation',
            name='description',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
