# Generated by Django 6.1.1 on 2026-09-14 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeAnnonceur', models.CharField(choices=[('Entreprise', 'Entreprise'), ('Particulier', 'Particulier')], max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('company_phone', models.CharField(max_length=15)),
                ('company_website', models.URLField(blank=True)),
                ('company_secteur', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('company_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='announcer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
