# Generated by Django 6.1.1 on 2026-09-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcer',
            name='company_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='announcer',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='announcer',
            name='company_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='announcer',
            name='company_secteur',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='announcer',
            name='description',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='announcer',
            name='typeAnnonceur',
            field=models.CharField(blank=True, choices=[('Entreprise', 'Entreprise'), ('Particulier', 'Particulier')], default='', max_length=100),
        ),
    ]
