# Generated by Django 5.2.17 on 2026-09-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcer', '0002_alter_announcer_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
